/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shelter;

/**
 *
 * @author rafaelsoriadiez
 */
public class Login extends javax.swing.JPanel {

    private Usuario us;
    private String usuario;
    private String ip;
    private int puerto;
    private String password;
    private String confirmar;
    private boolean ok;
    private ConexionServidor cs;
    
    
    public Login(Usuario us) {
        initComponents();
        this.us = us;
        setMensaje("hoka");
    }
    
    public void Visible(){
        this.setVisible(true);
    }
    
    //metodos gets
    public String getUsuario(){return usuario;}
    public String getIP(){return ip;}
    public int getPuerto(){return puerto;}
    public String getPassword(){return password;}
    public boolean getOk(){return ok;}

    
    public void setUsuario(){
        usuario = textNombre.getText();
        ip = textIP.getText();
        puerto = Integer.parseInt(textPuerto.getText());
        password = textPassword.getText();
    }
    
    public void setMensaje(String m){
        labelMensaje.setText(m);
    }
    
    public boolean iguales(String p1,String p2){
        if(p1.equals(p2)) return true;
        return false;
    }
    
    //validamos si hay datos para mandarselo al servidor
    public boolean comprobar(){
        if(iguales(password,confirmar)){
            if(usuario != null && ip != null) return true;
        }
        return false;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelText = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textPassword = new javax.swing.JTextField();
        textConfirmar = new javax.swing.JTextField();
        textIP = new javax.swing.JTextField();
        textPuerto = new javax.swing.JTextField();
        botonEnviar = new javax.swing.JButton();
        labelMensaje = new javax.swing.JLabel();
        butonAtras = new javax.swing.JButton();

        labelText.setText("Nombre");

        labelPassword.setText("Contraseña");

        jLabel1.setText("Confirmar contraseña");

        jLabel2.setText("IP");

        jLabel3.setText("Puerto");

        textPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPasswordActionPerformed(evt);
            }
        });

        textIP.setText("localhost");

        textPuerto.setText("4000");
        textPuerto.setToolTipText("");

        botonEnviar.setText("Enviar");
        botonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarActionPerformed(evt);
            }
        });

        butonAtras.setText("Atras");
        butonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelText)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(labelPassword)
                            .addComponent(labelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textNombre)
                            .addComponent(textPassword)
                            .addComponent(textConfirmar)
                            .addComponent(textIP)
                            .addComponent(textPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(butonAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelText)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEnviar)
                    .addComponent(butonAtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(labelMensaje)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPasswordActionPerformed
        
        
    }//GEN-LAST:event_textPasswordActionPerformed

    private void butonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonAtrasActionPerformed
        this.setVisible(false);
        us.setVisibleALL(true);
        
    }//GEN-LAST:event_butonAtrasActionPerformed

    private void botonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarActionPerformed
        usuario = textNombre.getText();
        ip = textIP.getText();
        password = textPassword.getText();
        confirmar = textConfirmar.getText();
        labelMensaje.setText("asdas.");
        
        if(!iguales(password,confirmar)){
            setMensaje("Error, las contraseñas son distintas.");
        }else{
            try{
                puerto = Integer.parseInt(textPuerto.getText());
                //Usuario actual = new Usuario(usuario,password,ip,puerto);
                //cs = new ConexionServidor(actual,password);
                this.setVisible(false);
                us.setVisible(false);
                //us.setVisibleALL(true);
            } catch (NumberFormatException nfe){
                setMensaje("En el campo puerto hay que introducir un número.");
            }
            
        }
    }//GEN-LAST:event_botonEnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEnviar;
    private javax.swing.JButton butonAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelText;
    private javax.swing.JTextField textConfirmar;
    private javax.swing.JTextField textIP;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPassword;
    private javax.swing.JTextField textPuerto;
    // End of variables declaration//GEN-END:variables
}
